// 11-0 player database.
// roles: opener | batter | keeper | allrounder | spinner | pacer
// rating: 70-99 overall used by the simulation engine.
// cred: one-line credential shown in Classic mode (hidden in CricIQ).

const TEAMS = {
  IND: { name: "India",        flag: "🇮🇳" },
  AUS: { name: "Australia",    flag: "🇦🇺" },
  ENG: { name: "England",      flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  PAK: { name: "Pakistan",     flag: "🇵🇰" },
  WI:  { name: "West Indies",  flag: "🌴" },
  SA:  { name: "South Africa", flag: "🇿🇦" },
  NZ:  { name: "New Zealand",  flag: "🇳🇿" },
  SL:  { name: "Sri Lanka",    flag: "🇱🇰" },
  BAN: { name: "Bangladesh",   flag: "🇧🇩" },
  ZIM: { name: "Zimbabwe",     flag: "🇿🇼" },
  AFG: { name: "Afghanistan",  flag: "🇦🇫" },
};

const DECADES = ["1970s", "1980s", "1990s", "2000s", "2010s", "2020s"];

const PLAYERS = [
  // ===================== INDIA =====================
  { name: "Sunil Gavaskar", team: "IND", decades: ["1970s","1980s"], roles: ["opener"], rating: 95, cred: "10,122 Test runs without a helmet vs the scariest pace ever" },
  { name: "Gundappa Viswanath", team: "IND", decades: ["1970s","1980s"], roles: ["batter"], rating: 88, cred: "Wristy genius — India never lost a Test when he scored a ton" },
  { name: "Farokh Engineer", team: "IND", decades: ["1970s"], roles: ["keeper"], rating: 82, cred: "Dashing keeper-bat of the spin quartet era" },
  { name: "Bishan Singh Bedi", team: "IND", decades: ["1970s"], roles: ["spinner"], rating: 89, cred: "266 Test wickets of pure left-arm loop and guile" },
  { name: "B.S. Chandrasekhar", team: "IND", decades: ["1970s"], roles: ["spinner"], rating: 87, cred: "Unreadable leg-spin; won India The Oval 1971" },
  { name: "Erapalli Prasanna", team: "IND", decades: ["1970s"], roles: ["spinner"], rating: 86, cred: "Off-spin maestro of flight and deception" },
  { name: "Mohinder Amarnath", team: "IND", decades: ["1970s","1980s"], roles: ["allrounder","batter"], rating: 85, cred: "Man of the Match in the 1983 semi AND final" },
  { name: "Madan Lal", team: "IND", decades: ["1970s","1980s"], roles: ["pacer"], rating: 78, cred: "Took Viv's wicket in the 1983 final" },
  { name: "Kapil Dev", team: "IND", decades: ["1980s","1990s"], roles: ["allrounder","pacer"], rating: 95, cred: "434 Test wkts + that 175* — India's greatest all-rounder" },
  { name: "Dilip Vengsarkar", team: "IND", decades: ["1980s"], roles: ["batter"], rating: 86, cred: "Three Test tons at Lord's — the Colonel" },
  { name: "Krishnamachari Srikkanth", team: "IND", decades: ["1980s"], roles: ["opener"], rating: 82, cred: "Top-scored in the 1983 World Cup final" },
  { name: "Ravi Shastri", team: "IND", decades: ["1980s"], roles: ["allrounder","spinner"], rating: 83, cred: "Champion of Champions 1985 + Audi" },
  { name: "Syed Kirmani", team: "IND", decades: ["1980s"], roles: ["keeper"], rating: 84, cred: "Best keeper of the 1983 World Cup" },
  { name: "Roger Binny", team: "IND", decades: ["1980s"], roles: ["pacer","allrounder"], rating: 79, cred: "Leading wicket-taker of the 1983 World Cup" },
  { name: "Sachin Tendulkar", team: "IND", decades: ["1990s","2000s","2010s"], roles: ["opener","batter"], rating: 98, cred: "100 international hundreds. 34,357 intl runs. God." },
  { name: "Mohammad Azharuddin", team: "IND", decades: ["1980s","1990s"], roles: ["batter"], rating: 87, cred: "Silken wrists, three tons in his first three Tests" },
  { name: "Navjot Singh Sidhu", team: "IND", decades: ["1990s"], roles: ["opener"], rating: 81, cred: "Sixer Sidhu — spinners' nightmare" },
  { name: "Anil Kumble", team: "IND", decades: ["1990s","2000s"], roles: ["spinner"], rating: 93, cred: "619 Test wickets incl. all 10 in an innings" },
  { name: "Javagal Srinath", team: "IND", decades: ["1990s","2000s"], roles: ["pacer"], rating: 86, cred: "India's fastest of the 90s — 315 ODI wickets" },
  { name: "Venkatesh Prasad", team: "IND", decades: ["1990s"], roles: ["pacer"], rating: 80, cred: "Ask Aamir Sohail about the send-off" },
  { name: "Nayan Mongia", team: "IND", decades: ["1990s"], roles: ["keeper"], rating: 79, cred: "Safe hands behind the stumps through the 90s" },
  { name: "Sourav Ganguly", team: "IND", decades: ["1990s","2000s"], roles: ["opener","batter"], rating: 90, cred: "Dada. God of the off side. Shirt at Lord's." },
  { name: "Rahul Dravid", team: "IND", decades: ["1990s","2000s","2010s"], roles: ["batter"], rating: 94, cred: "The Wall — 13,288 Test runs, 31,258 balls faced" },
  { name: "VVS Laxman", team: "IND", decades: ["1990s","2000s"], roles: ["batter"], rating: 89, cred: "281 at Eden Gardens. Very Very Special." },
  { name: "Virender Sehwag", team: "IND", decades: ["2000s","2010s"], roles: ["opener"], rating: 91, cred: "Two Test triple centuries at a strike rate of 82" },
  { name: "Yuvraj Singh", team: "IND", decades: ["2000s","2010s"], roles: ["batter","allrounder"], rating: 88, cred: "Six sixes + Player of the Tournament, WC 2011" },
  { name: "MS Dhoni", team: "IND", decades: ["2000s","2010s"], roles: ["keeper"], rating: 95, cred: "Captain Cool — only skipper with all 3 ICC trophies" },
  { name: "Zaheer Khan", team: "IND", decades: ["2000s","2010s"], roles: ["pacer"], rating: 88, cred: "Joint-highest wicket-taker, WC 2011" },
  { name: "Harbhajan Singh", team: "IND", decades: ["2000s","2010s"], roles: ["spinner"], rating: 87, cred: "Turbanator — hat-trick vs Australia, Eden 2001" },
  { name: "Gautam Gambhir", team: "IND", decades: ["2000s","2010s"], roles: ["opener"], rating: 84, cred: "97 in the 2011 final, 75 in the 2007 final" },
  { name: "Ashish Nehra", team: "IND", decades: ["2000s","2010s"], roles: ["pacer"], rating: 80, cred: "6/23 vs England, WC 2003" },
  { name: "Irfan Pathan", team: "IND", decades: ["2000s"], roles: ["allrounder","pacer"], rating: 81, cred: "Test hat-trick in the first over vs Pakistan" },
  { name: "Suresh Raina", team: "IND", decades: ["2000s","2010s"], roles: ["batter"], rating: 83, cred: "Mr IPL — clutch in both 2011 WC knockouts" },
  { name: "Virat Kohli", team: "IND", decades: ["2010s","2020s"], roles: ["batter"], rating: 97, cred: "50 ODI tons — the king of the chase" },
  { name: "Rohit Sharma", team: "IND", decades: ["2010s","2020s"], roles: ["opener"], rating: 93, cred: "Three ODI double hundreds. Hitman." },
  { name: "Shikhar Dhawan", team: "IND", decades: ["2010s"], roles: ["opener"], rating: 85, cred: "Gabbar — ICC tournament specialist" },
  { name: "Cheteshwar Pujara", team: "IND", decades: ["2010s","2020s"], roles: ["batter"], rating: 86, cred: "Wore down Australia in their own backyard, twice" },
  { name: "Ajinkya Rahane", team: "IND", decades: ["2010s"], roles: ["batter"], rating: 83, cred: "MCG 2020 ton that turned a series" },
  { name: "Ravichandran Ashwin", team: "IND", decades: ["2010s","2020s"], roles: ["spinner"], rating: 92, cred: "500+ Test wickets, fastest Indian there" },
  { name: "Ravindra Jadeja", team: "IND", decades: ["2010s","2020s"], roles: ["allrounder","spinner"], rating: 91, cred: "Sir Jadeja — bat, ball, and a rocket arm" },
  { name: "Jasprit Bumrah", team: "IND", decades: ["2010s","2020s"], roles: ["pacer"], rating: 96, cred: "Best bowler alive. Yorkers from another planet." },
  { name: "Mohammed Shami", team: "IND", decades: ["2010s","2020s"], roles: ["pacer"], rating: 89, cred: "7/57 in a World Cup semi-final" },
  { name: "Ishant Sharma", team: "IND", decades: ["2010s"], roles: ["pacer"], rating: 82, cred: "100+ Tests of hitting the deck hard" },
  { name: "Bhuvneshwar Kumar", team: "IND", decades: ["2010s"], roles: ["pacer"], rating: 83, cred: "Swing both ways, in any conditions" },
  { name: "KL Rahul", team: "IND", decades: ["2010s","2020s"], roles: ["opener","keeper"], rating: 85, cred: "Classy everywhere from 1 to 6, gloves included" },
  { name: "Rishabh Pant", team: "IND", decades: ["2010s","2020s"], roles: ["keeper"], rating: 89, cred: "Gabba 2021. Spidey-cam celebrations." },
  { name: "Hardik Pandya", team: "IND", decades: ["2010s","2020s"], roles: ["allrounder"], rating: 86, cred: "India's seam-bowling all-rounder unicorn" },
  { name: "Shubman Gill", team: "IND", decades: ["2020s"], roles: ["opener"], rating: 88, cred: "The Prince — generational timing" },
  { name: "Suryakumar Yadav", team: "IND", decades: ["2020s"], roles: ["batter"], rating: 86, cred: "SKY — 360° T20 sorcery" },
  { name: "Shreyas Iyer", team: "IND", decades: ["2020s"], roles: ["batter"], rating: 84, cred: "No. 4 solved. Pull shot merchant." },
  { name: "Mohammed Siraj", team: "IND", decades: ["2020s"], roles: ["pacer"], rating: 86, cred: "6/21 in an Asia Cup final" },
  { name: "Kuldeep Yadav", team: "IND", decades: ["2010s","2020s"], roles: ["spinner"], rating: 85, cred: "Left-arm wrist spin — batters still can't read him" },
  { name: "Yashasvi Jaiswal", team: "IND", decades: ["2020s"], roles: ["opener"], rating: 86, cred: "From Mumbai maidans to double tons vs England" },
  { name: "Axar Patel", team: "IND", decades: ["2020s"], roles: ["allrounder","spinner"], rating: 83, cred: "Bapu — arm-balls and big finals runs" },

  // ===================== AUSTRALIA =====================
  { name: "Greg Chappell", team: "AUS", decades: ["1970s","1980s"], roles: ["batter"], rating: 93, cred: "Australia's classiest bat of his era — avg 53.86" },
  { name: "Ian Chappell", team: "AUS", decades: ["1970s"], roles: ["batter"], rating: 89, cred: "Hard-nosed captain who never took a backward step" },
  { name: "Dennis Lillee", team: "AUS", decades: ["1970s","1980s"], roles: ["pacer"], rating: 95, cred: "355 Test wickets of pure theatre and menace" },
  { name: "Jeff Thomson", team: "AUS", decades: ["1970s","1980s"], roles: ["pacer"], rating: 90, cred: "Fastest bowler ever clocked by fear" },
  { name: "Rod Marsh", team: "AUS", decades: ["1970s","1980s"], roles: ["keeper"], rating: 87, cred: "'Caught Marsh, bowled Lillee' x95" },
  { name: "Doug Walters", team: "AUS", decades: ["1970s"], roles: ["batter"], rating: 84, cred: "Century in a session, more than once" },
  { name: "Allan Border", team: "AUS", decades: ["1980s","1990s"], roles: ["batter"], rating: 92, cred: "11,174 Test runs carrying Australia through the dark years" },
  { name: "Kim Hughes", team: "AUS", decades: ["1980s"], roles: ["batter"], rating: 81, cred: "Counter-attacked the great WI pace quartet" },
  { name: "David Boon", team: "AUS", decades: ["1980s","1990s"], roles: ["opener","batter"], rating: 85, cred: "Moustache, short leg catches, and 7,422 Test runs" },
  { name: "Craig McDermott", team: "AUS", decades: ["1980s","1990s"], roles: ["pacer"], rating: 84, cred: "291 Test wickets of red-headed fury" },
  { name: "Dean Jones", team: "AUS", decades: ["1980s","1990s"], roles: ["batter"], rating: 85, cred: "Redefined ODI batting — and that tied-Test 210" },
  { name: "Mark Taylor", team: "AUS", decades: ["1990s"], roles: ["opener"], rating: 86, cred: "Declared on 334* to share Bradman's mark" },
  { name: "Michael Slater", team: "AUS", decades: ["1990s"], roles: ["opener"], rating: 83, cred: "Attacked the new ball before it was fashionable" },
  { name: "Steve Waugh", team: "AUS", decades: ["1980s","1990s","2000s"], roles: ["batter","allrounder"], rating: 92, cred: "Mentally toughest man to ever wear the baggy green" },
  { name: "Mark Waugh", team: "AUS", decades: ["1990s","2000s"], roles: ["batter"], rating: 88, cred: "The most elegant 153 Tests you'll ever see" },
  { name: "Ian Healy", team: "AUS", decades: ["1990s"], roles: ["keeper"], rating: 86, cred: "395 dismissals standing up to Warne" },
  { name: "Shane Warne", team: "AUS", decades: ["1990s","2000s"], roles: ["spinner"], rating: 97, cred: "708 Test wickets. Ball of the Century. Showman." },
  { name: "Glenn McGrath", team: "AUS", decades: ["1990s","2000s"], roles: ["pacer"], rating: 96, cred: "563 Test wickets on a 10-cent piece" },
  { name: "Adam Gilchrist", team: "AUS", decades: ["1990s","2000s"], roles: ["keeper","opener"], rating: 94, cred: "Walked in at 7 and ended careers — 3 WC finals, 3 wins" },
  { name: "Matthew Hayden", team: "AUS", decades: ["2000s"], roles: ["opener"], rating: 91, cred: "Bullied new-ball bowlers for a living" },
  { name: "Justin Langer", team: "AUS", decades: ["1990s","2000s"], roles: ["opener"], rating: 85, cred: "Hayden's partner in 5,655 runs of crime" },
  { name: "Ricky Ponting", team: "AUS", decades: ["1990s","2000s","2010s"], roles: ["batter"], rating: 95, cred: "Punter — 140* in a World Cup final, twice a WC-winning captain" },
  { name: "Damien Martyn", team: "AUS", decades: ["2000s"], roles: ["batter"], rating: 85, cred: "Silk at No.4 in the greatest ODI side ever" },
  { name: "Michael Hussey", team: "AUS", decades: ["2000s","2010s"], roles: ["batter"], rating: 87, cred: "Mr Cricket — debut avg above 80 for years" },
  { name: "Andrew Symonds", team: "AUS", decades: ["2000s"], roles: ["allrounder"], rating: 84, cred: "143* off 125 to flip the 2003 World Cup" },
  { name: "Brett Lee", team: "AUS", decades: ["2000s"], roles: ["pacer"], rating: 88, cred: "100mph smile, 690 international wickets" },
  { name: "Jason Gillespie", team: "AUS", decades: ["1990s","2000s"], roles: ["pacer"], rating: 85, cred: "McGrath's perfect partner — and a Test 201* as nightwatchman" },
  { name: "Michael Clarke", team: "AUS", decades: ["2000s","2010s"], roles: ["batter"], rating: 88, cred: "329* at the SCG; WC-winning captain 2015" },
  { name: "Mitchell Johnson", team: "AUS", decades: ["2000s","2010s"], roles: ["pacer"], rating: 89, cred: "37 wickets of terror in one Ashes" },
  { name: "Shane Watson", team: "AUS", decades: ["2000s","2010s"], roles: ["allrounder","opener"], rating: 85, cred: "When fit, the best all-round package in white-ball cricket" },
  { name: "Brad Haddin", team: "AUS", decades: ["2010s"], roles: ["keeper"], rating: 82, cred: "Clutch with the gloves in the 2015 WC win" },
  { name: "David Warner", team: "AUS", decades: ["2010s","2020s"], roles: ["opener"], rating: 90, cred: "From T20 pinch-hitter to 100 international caps everywhere" },
  { name: "Steve Smith", team: "AUS", decades: ["2010s","2020s"], roles: ["batter"], rating: 95, cred: "Best Test bat since Bradman, fidgets included" },
  { name: "Mitchell Starc", team: "AUS", decades: ["2010s","2020s"], roles: ["pacer"], rating: 91, cred: "Most WC wickets in a single edition (27)" },
  { name: "Pat Cummins", team: "AUS", decades: ["2010s","2020s"], roles: ["pacer"], rating: 93, cred: "Captained Australia to WTC + ODI WC in one year" },
  { name: "Josh Hazlewood", team: "AUS", decades: ["2010s","2020s"], roles: ["pacer"], rating: 89, cred: "McGrath 2.0 — relentless top of off" },
  { name: "Nathan Lyon", team: "AUS", decades: ["2010s","2020s"], roles: ["spinner"], rating: 89, cred: "GOAT — 500+ Test wickets of off-spin" },
  { name: "Glenn Maxwell", team: "AUS", decades: ["2010s","2020s"], roles: ["allrounder","batter"], rating: 85, cred: "201* on one leg vs Afghanistan. Enough said." },
  { name: "Aaron Finch", team: "AUS", decades: ["2010s","2020s"], roles: ["opener"], rating: 83, cred: "172 in a T20I — twice broke the format's record" },
  { name: "Travis Head", team: "AUS", decades: ["2010s","2020s"], roles: ["opener","batter"], rating: 88, cred: "Centuries in a WTC final AND a World Cup final" },
  { name: "Marnus Labuschagne", team: "AUS", decades: ["2020s"], roles: ["batter"], rating: 86, cred: "Concussion sub to world No.1 Test bat" },
  { name: "Alex Carey", team: "AUS", decades: ["2020s"], roles: ["keeper"], rating: 82, cred: "Tidy gloves and that Lord's stumping" },
  { name: "Mitchell Marsh", team: "AUS", decades: ["2010s","2020s"], roles: ["allrounder"], rating: 83, cred: "Put the World Cup trophy where? Exactly." },
  { name: "Adam Zampa", team: "AUS", decades: ["2010s","2020s"], roles: ["spinner"], rating: 84, cred: "White-ball leg-spin banker" },
  { name: "Cameron Green", team: "AUS", decades: ["2020s"], roles: ["allrounder"], rating: 84, cred: "Two-metre all-round prototype" },

  // ===================== ENGLAND =====================
  { name: "Geoffrey Boycott", team: "ENG", decades: ["1970s","1980s"], roles: ["opener"], rating: 90, cred: "8,114 Test runs and not one careless shot" },
  { name: "John Snow", team: "ENG", decades: ["1970s"], roles: ["pacer"], rating: 86, cred: "England's spearhead of the early 70s" },
  { name: "Alan Knott", team: "ENG", decades: ["1970s"], roles: ["keeper"], rating: 88, cred: "Arguably the finest pure gloveman ever" },
  { name: "Derek Underwood", team: "ENG", decades: ["1970s","1980s"], roles: ["spinner"], rating: 88, cred: "'Deadly' — unplayable on anything damp" },
  { name: "Tony Greig", team: "ENG", decades: ["1970s"], roles: ["allrounder"], rating: 85, cred: "6'6\" of all-round provocation" },
  { name: "Bob Willis", team: "ENG", decades: ["1970s","1980s"], roles: ["pacer"], rating: 87, cred: "8/43 at Headingley 1981, eyes blazing" },
  { name: "Ian Botham", team: "ENG", decades: ["1980s","1990s"], roles: ["allrounder"], rating: 94, cred: "Beefy — won the 1981 Ashes basically alone" },
  { name: "David Gower", team: "ENG", decades: ["1980s","1990s"], roles: ["batter"], rating: 89, cred: "Lazy elegance, 8,231 Test runs" },
  { name: "Graham Gooch", team: "ENG", decades: ["1980s","1990s"], roles: ["opener"], rating: 89, cred: "333 at Lord's; most runs in first-class history" },
  { name: "Mike Gatting", team: "ENG", decades: ["1980s"], roles: ["batter"], rating: 83, cred: "Ashes-winning captain '86-87" },
  { name: "Allan Lamb", team: "ENG", decades: ["1980s"], roles: ["batter"], rating: 84, cred: "Stood up to the WI quicks when few could" },
  { name: "Jack Russell", team: "ENG", decades: ["1990s"], roles: ["keeper"], rating: 81, cred: "Eccentric genius behind the stumps" },
  { name: "Alec Stewart", team: "ENG", decades: ["1990s","2000s"], roles: ["keeper","opener"], rating: 84, cred: "8,463 Test runs as keeper-opener workhorse" },
  { name: "Michael Atherton", team: "ENG", decades: ["1990s","2000s"], roles: ["opener"], rating: 85, cred: "185* in Jo'burg — 10 hours of defiance" },
  { name: "Graham Thorpe", team: "ENG", decades: ["1990s","2000s"], roles: ["batter"], rating: 85, cred: "England's best vs pace and spin alike" },
  { name: "Darren Gough", team: "ENG", decades: ["1990s","2000s"], roles: ["pacer"], rating: 84, cred: "Heart of a lion, hat-trick at the SCG" },
  { name: "Phil Tufnell", team: "ENG", decades: ["1990s"], roles: ["spinner"], rating: 79, cred: "Left-arm spin and left-field comedy" },
  { name: "Nasser Hussain", team: "ENG", decades: ["1990s","2000s"], roles: ["batter"], rating: 83, cred: "Rebuilt England's spine as captain" },
  { name: "Marcus Trescothick", team: "ENG", decades: ["2000s"], roles: ["opener"], rating: 84, cred: "Banged it through the covers off either foot" },
  { name: "Michael Vaughan", team: "ENG", decades: ["2000s"], roles: ["opener","batter"], rating: 84, cred: "2005 Ashes-winning captain" },
  { name: "Andrew Flintoff", team: "ENG", decades: ["2000s"], roles: ["allrounder"], rating: 88, cred: "Freddie — 2005 Ashes folk hero" },
  { name: "Kevin Pietersen", team: "ENG", decades: ["2000s","2010s"], roles: ["batter"], rating: 90, cred: "Switch-hits and 8,181 Test runs of swagger" },
  { name: "Steve Harmison", team: "ENG", decades: ["2000s"], roles: ["pacer"], rating: 83, cred: "7/12 at Sabina Park" },
  { name: "Matt Prior", team: "ENG", decades: ["2000s","2010s"], roles: ["keeper"], rating: 83, cred: "Engine room of England's No.1 Test side" },
  { name: "Paul Collingwood", team: "ENG", decades: ["2000s","2010s"], roles: ["batter","allrounder"], rating: 82, cred: "England's first ICC-trophy-winning captain" },
  { name: "Graeme Swann", team: "ENG", decades: ["2000s","2010s"], roles: ["spinner"], rating: 87, cred: "255 Test wickets and a first-over wicket habit" },
  { name: "James Anderson", team: "ENG", decades: ["2000s","2010s","2020s"], roles: ["pacer"], rating: 93, cred: "704 Test wickets — most ever by a pacer" },
  { name: "Stuart Broad", team: "ENG", decades: ["2000s","2010s","2020s"], roles: ["pacer"], rating: 90, cred: "8/15 at Trent Bridge; 600+ Test wickets" },
  { name: "Alastair Cook", team: "ENG", decades: ["2000s","2010s"], roles: ["opener"], rating: 90, cred: "12,472 Test runs, 766 in one Ashes" },
  { name: "Ian Bell", team: "ENG", decades: ["2000s","2010s"], roles: ["batter"], rating: 84, cred: "Five Ashes wins of pure timing" },
  { name: "Jonathan Trott", team: "ENG", decades: ["2010s"], roles: ["batter"], rating: 83, cred: "Guarded No.3 — scratch, mark, repeat, win" },
  { name: "Joe Root", team: "ENG", decades: ["2010s","2020s"], roles: ["batter"], rating: 94, cred: "England's all-time leading Test run-scorer" },
  { name: "Ben Stokes", team: "ENG", decades: ["2010s","2020s"], roles: ["allrounder"], rating: 92, cred: "Headingley 2019 + WC final 2019. Big-game cheat code." },
  { name: "Jos Buttler", team: "ENG", decades: ["2010s","2020s"], roles: ["keeper"], rating: 88, cred: "White-ball finisher from another dimension" },
  { name: "Jonny Bairstow", team: "ENG", decades: ["2010s","2020s"], roles: ["keeper","batter"], rating: 84, cred: "Bazball's original wrecking ball" },
  { name: "Eoin Morgan", team: "ENG", decades: ["2010s","2020s"], roles: ["batter"], rating: 85, cred: "Rebuilt England into 2019 world champions" },
  { name: "Moeen Ali", team: "ENG", decades: ["2010s","2020s"], roles: ["allrounder","spinner"], rating: 82, cred: "Beard that's feared — 3,000 runs & 200 Test wickets" },
  { name: "Adil Rashid", team: "ENG", decades: ["2010s","2020s"], roles: ["spinner"], rating: 84, cred: "England's white-ball spin lynchpin" },
  { name: "Jofra Archer", team: "ENG", decades: ["2010s","2020s"], roles: ["pacer"], rating: 86, cred: "Super Over ice in the 2019 final" },
  { name: "Mark Wood", team: "ENG", decades: ["2010s","2020s"], roles: ["pacer"], rating: 84, cred: "96mph on an imaginary horse" },
  { name: "Harry Brook", team: "ENG", decades: ["2020s"], roles: ["batter"], rating: 87, cred: "Strike-rate of a T20, average of a Test great" },
  { name: "Zak Crawley", team: "ENG", decades: ["2020s"], roles: ["opener"], rating: 80, cred: "267 at the Rose Bowl — drives like a dream" },
  { name: "Ollie Pope", team: "ENG", decades: ["2020s"], roles: ["batter"], rating: 81, cred: "196 in Hyderabad to stun India" },
  { name: "Chris Woakes", team: "ENG", decades: ["2010s","2020s"], roles: ["pacer","allrounder"], rating: 83, cred: "Mr Reliable with bat and new ball" },

  // ===================== PAKISTAN =====================
  { name: "Majid Khan", team: "PAK", decades: ["1970s","1980s"], roles: ["opener"], rating: 86, cred: "Century before lunch on day one" },
  { name: "Zaheer Abbas", team: "PAK", decades: ["1970s","1980s"], roles: ["batter"], rating: 90, cred: "The Asian Bradman — 100 first-class hundreds" },
  { name: "Asif Iqbal", team: "PAK", decades: ["1970s"], roles: ["batter","allrounder"], rating: 84, cred: "Dazzling counter-attacker and captain" },
  { name: "Sadiq Mohammad", team: "PAK", decades: ["1970s"], roles: ["opener"], rating: 80, cred: "Fearless left-handed opener of the 70s" },
  { name: "Sarfraz Nawaz", team: "PAK", decades: ["1970s","1980s"], roles: ["pacer"], rating: 85, cred: "Godfather of reverse swing" },
  { name: "Wasim Bari", team: "PAK", decades: ["1970s","1980s"], roles: ["keeper"], rating: 83, cred: "Pakistan's safest pair of gloves" },
  { name: "Imran Khan", team: "PAK", decades: ["1970s","1980s","1990s"], roles: ["allrounder","pacer"], rating: 96, cred: "Cornered tigers, 1992. The complete cricketer." },
  { name: "Javed Miandad", team: "PAK", decades: ["1970s","1980s","1990s"], roles: ["batter"], rating: 93, cred: "Last-ball six at Sharjah — street-fighter supreme" },
  { name: "Abdul Qadir", team: "PAK", decades: ["1980s"], roles: ["spinner"], rating: 88, cred: "Kept leg-spin alive for Warne to inherit" },
  { name: "Mohsin Khan", team: "PAK", decades: ["1980s"], roles: ["opener"], rating: 80, cred: "200 at Lord's, 1982" },
  { name: "Mudassar Nazar", team: "PAK", decades: ["1980s"], roles: ["opener","allrounder"], rating: 81, cred: "Golden-arm seamers and gritty opening" },
  { name: "Wasim Akram", team: "PAK", decades: ["1980s","1990s","2000s"], roles: ["pacer","allrounder"], rating: 97, cred: "Sultan of Swing — 916 international wickets" },
  { name: "Waqar Younis", team: "PAK", decades: ["1990s","2000s"], roles: ["pacer"], rating: 93, cred: "Toe-crushing yorkers at 150kph" },
  { name: "Saeed Anwar", team: "PAK", decades: ["1990s","2000s"], roles: ["opener"], rating: 89, cred: "194 in Chennai — silk against anyone" },
  { name: "Aamer Sohail", team: "PAK", decades: ["1990s"], roles: ["opener"], rating: 81, cred: "Aggressive left-hander of the 1992 champions" },
  { name: "Inzamam-ul-Haq", team: "PAK", decades: ["1990s","2000s"], roles: ["batter"], rating: 91, cred: "Inzi — destroyer of attacks (when not running)" },
  { name: "Saleem Malik", team: "PAK", decades: ["1980s","1990s"], roles: ["batter"], rating: 84, cred: "Wrists that made spin bowling look unfair" },
  { name: "Rashid Latif", team: "PAK", decades: ["1990s"], roles: ["keeper"], rating: 80, cred: "Acrobatic gloveman of the 90s" },
  { name: "Moin Khan", team: "PAK", decades: ["1990s","2000s"], roles: ["keeper"], rating: 82, cred: "'Shabash shabash' — fighter at No.7" },
  { name: "Saqlain Mushtaq", team: "PAK", decades: ["1990s","2000s"], roles: ["spinner"], rating: 89, cred: "Invented the doosra. Chennai 1999." },
  { name: "Mushtaq Ahmed", team: "PAK", decades: ["1990s"], roles: ["spinner"], rating: 85, cred: "Leg-spin star of the 1992 World Cup win" },
  { name: "Shoaib Akhtar", team: "PAK", decades: ["1990s","2000s"], roles: ["pacer"], rating: 90, cred: "Rawalpindi Express — 161.3 kph, fastest ever" },
  { name: "Shahid Afridi", team: "PAK", decades: ["1990s","2000s","2010s"], roles: ["allrounder","spinner"], rating: 85, cred: "Boom Boom — 37-ball ODI ton at 16" },
  { name: "Mohammad Yousuf", team: "PAK", decades: ["2000s"], roles: ["batter"], rating: 89, cred: "1,788 Test runs in a calendar year — record" },
  { name: "Younis Khan", team: "PAK", decades: ["2000s","2010s"], roles: ["batter"], rating: 90, cred: "10,099 Test runs; T20 WC-winning captain" },
  { name: "Misbah-ul-Haq", team: "PAK", decades: ["2000s","2010s"], roles: ["batter"], rating: 86, cred: "Took Pakistan to Test No.1 at 42" },
  { name: "Kamran Akmal", team: "PAK", decades: ["2000s","2010s"], roles: ["keeper"], rating: 79, cred: "Dangerous top-order hitter with the gloves" },
  { name: "Umar Gul", team: "PAK", decades: ["2000s","2010s"], roles: ["pacer"], rating: 82, cred: "Death-overs yorker king of early T20" },
  { name: "Saeed Ajmal", team: "PAK", decades: ["2000s","2010s"], roles: ["spinner"], rating: 87, cred: "World's best spinner 2011-13" },
  { name: "Mohammad Hafeez", team: "PAK", decades: ["2000s","2010s"], roles: ["allrounder","opener"], rating: 81, cred: "The Professor — 392 international caps" },
  { name: "Sarfaraz Ahmed", team: "PAK", decades: ["2010s"], roles: ["keeper"], rating: 80, cred: "Champions Trophy 2017 winning captain" },
  { name: "Babar Azam", team: "PAK", decades: ["2010s","2020s"], roles: ["batter"], rating: 91, cred: "Cover drive heir to the throne" },
  { name: "Mohammad Rizwan", team: "PAK", decades: ["2020s"], roles: ["keeper"], rating: 86, cred: "Most T20I runs in a calendar year" },
  { name: "Shaheen Shah Afridi", team: "PAK", decades: ["2010s","2020s"], roles: ["pacer"], rating: 89, cred: "First-over wicket guaranteed (ask India, MCG aside)" },
  { name: "Naseem Shah", team: "PAK", decades: ["2020s"], roles: ["pacer"], rating: 84, cred: "Test hat-trick as a teenager" },
  { name: "Haris Rauf", team: "PAK", decades: ["2020s"], roles: ["pacer"], rating: 82, cred: "150kph from tape-ball streets" },
  { name: "Shadab Khan", team: "PAK", decades: ["2010s","2020s"], roles: ["allrounder","spinner"], rating: 81, cred: "Leggie, finisher, livewire fielder" },
  { name: "Fakhar Zaman", team: "PAK", decades: ["2010s","2020s"], roles: ["opener"], rating: 83, cred: "114 vs India in a Champions Trophy final" },
  { name: "Yasir Shah", team: "PAK", decades: ["2010s"], roles: ["spinner"], rating: 84, cred: "Fastest to 200 Test wickets in 82 years" },

  // ===================== WEST INDIES =====================
  { name: "Clive Lloyd", team: "WI", decades: ["1970s","1980s"], roles: ["batter"], rating: 91, cred: "Supercat — captain of the most feared team ever" },
  { name: "Viv Richards", team: "WI", decades: ["1970s","1980s","1990s"], roles: ["batter"], rating: 97, cred: "No helmet. Chewing gum. Pure intimidation." },
  { name: "Gordon Greenidge", team: "WI", decades: ["1970s","1980s","1990s"], roles: ["opener"], rating: 91, cred: "Double ton in a day at Lord's — limping" },
  { name: "Desmond Haynes", team: "WI", decades: ["1980s","1990s"], roles: ["opener"], rating: 88, cred: "Greenidge's partner in 16 century stands" },
  { name: "Roy Fredericks", team: "WI", decades: ["1970s"], roles: ["opener"], rating: 84, cred: "Hooked Lillee for six, lost his hat, kept going" },
  { name: "Alvin Kallicharran", team: "WI", decades: ["1970s","1980s"], roles: ["batter"], rating: 85, cred: "Tiny left-hander, giant strokes" },
  { name: "Rohan Kanhai", team: "WI", decades: ["1970s"], roles: ["batter"], rating: 87, cred: "The falling hook shot — pure audacity" },
  { name: "Deryck Murray", team: "WI", decades: ["1970s","1980s"], roles: ["keeper"], rating: 81, cred: "Kept to the four horsemen without flinching" },
  { name: "Andy Roberts", team: "WI", decades: ["1970s","1980s"], roles: ["pacer"], rating: 91, cred: "Two bouncers: one you saw, one you didn't" },
  { name: "Michael Holding", team: "WI", decades: ["1970s","1980s"], roles: ["pacer"], rating: 93, cred: "Whispering Death — 14/149 at The Oval" },
  { name: "Joel Garner", team: "WI", decades: ["1970s","1980s"], roles: ["pacer"], rating: 92, cred: "Big Bird — yorkers from 11 feet in the sky" },
  { name: "Colin Croft", team: "WI", decades: ["1970s","1980s"], roles: ["pacer"], rating: 86, cred: "The nastiest angle in fast bowling" },
  { name: "Malcolm Marshall", team: "WI", decades: ["1980s","1990s"], roles: ["pacer"], rating: 96, cred: "376 Test wickets at 20.94 — the GOAT quick" },
  { name: "Jeff Dujon", team: "WI", decades: ["1980s","1990s"], roles: ["keeper"], rating: 86, cred: "Flying catches off the fastest attack ever" },
  { name: "Richie Richardson", team: "WI", decades: ["1980s","1990s"], roles: ["batter"], rating: 86, cred: "Maroon sun hat vs 90mph — no helmet needed" },
  { name: "Gus Logie", team: "WI", decades: ["1980s","1990s"], roles: ["batter"], rating: 80, cred: "Pocket dynamo in the middle order" },
  { name: "Curtly Ambrose", team: "WI", decades: ["1980s","1990s","2000s"], roles: ["pacer"], rating: 94, cred: "7/1 spell vs Australia. Speak to no man." },
  { name: "Courtney Walsh", team: "WI", decades: ["1980s","1990s","2000s"], roles: ["pacer"], rating: 91, cred: "First to 500 Test wickets" },
  { name: "Brian Lara", team: "WI", decades: ["1990s","2000s"], roles: ["batter"], rating: 96, cred: "375. 400*. 501*. The Prince of Port of Spain." },
  { name: "Carl Hooper", team: "WI", decades: ["1990s","2000s"], roles: ["allrounder","spinner"], rating: 82, cred: "Languid genius — off-spin and silk" },
  { name: "Jimmy Adams", team: "WI", decades: ["1990s"], roles: ["batter"], rating: 80, cred: "Briefly the world's No.1-ranked Test batter" },
  { name: "Shivnarine Chanderpaul", team: "WI", decades: ["1990s","2000s","2010s"], roles: ["batter"], rating: 89, cred: "Crab stance, 11,867 Test runs, impossible to remove" },
  { name: "Ridley Jacobs", team: "WI", decades: ["1990s","2000s"], roles: ["keeper"], rating: 79, cred: "Gritty keeper-bat of a tough era" },
  { name: "Chris Gayle", team: "WI", decades: ["2000s","2010s"], roles: ["opener"], rating: 89, cred: "Universe Boss — two Test triples + T20 carnage" },
  { name: "Ramnaresh Sarwan", team: "WI", decades: ["2000s","2010s"], roles: ["batter"], rating: 83, cred: "Elegant No.3 with a hook-shot addiction" },
  { name: "Marlon Samuels", team: "WI", decades: ["2000s","2010s"], roles: ["batter"], rating: 81, cred: "Match-winner in two T20 WC finals" },
  { name: "Dwayne Bravo", team: "WI", decades: ["2000s","2010s"], roles: ["allrounder"], rating: 84, cred: "Champion, champion — death-overs pioneer" },
  { name: "Kieron Pollard", team: "WI", decades: ["2010s","2020s"], roles: ["allrounder"], rating: 83, cred: "Six sixes in an over, franchise royalty" },
  { name: "Andre Russell", team: "WI", decades: ["2010s","2020s"], roles: ["allrounder"], rating: 85, cred: "Muscle Russell — most feared T20 finisher alive" },
  { name: "Sunil Narine", team: "WI", decades: ["2010s","2020s"], roles: ["spinner"], rating: 86, cred: "Mystery spin that broke the IPL" },
  { name: "Denesh Ramdin", team: "WI", decades: ["2000s","2010s"], roles: ["keeper"], rating: 78, cred: "Two T20 World Cup titles behind the stumps" },
  { name: "Darren Sammy", team: "WI", decades: ["2010s"], roles: ["allrounder","pacer"], rating: 79, cred: "Only captain with two T20 World Cups" },
  { name: "Jason Holder", team: "WI", decades: ["2010s","2020s"], roles: ["allrounder","pacer"], rating: 84, cred: "202* at No.8; world No.1 all-rounder" },
  { name: "Kemar Roach", team: "WI", decades: ["2010s","2020s"], roles: ["pacer"], rating: 84, cred: "Keeper of the great WI fast-bowling flame" },
  { name: "Shai Hope", team: "WI", decades: ["2010s","2020s"], roles: ["keeper","batter"], rating: 83, cred: "Twin tons at Headingley to chase down history" },
  { name: "Nicholas Pooran", team: "WI", decades: ["2020s"], roles: ["keeper","batter"], rating: 84, cred: "Wrists of steel, bat speed of a whip" },
  { name: "Shimron Hetmyer", team: "WI", decades: ["2020s"], roles: ["batter"], rating: 81, cred: "Ice-cold finisher when the lights are brightest" },
  { name: "Alzarri Joseph", team: "WI", decades: ["2020s"], roles: ["pacer"], rating: 82, cred: "Bowled an IPL 6/12 on debut" },
  { name: "Akeal Hosein", team: "WI", decades: ["2020s"], roles: ["spinner"], rating: 79, cred: "New-ball left-arm spin specialist" },
  { name: "Kraigg Brathwaite", team: "WI", decades: ["2010s","2020s"], roles: ["opener"], rating: 80, cred: "Old-school grit in a T20 world" },
  { name: "Brandon King", team: "WI", decades: ["2020s"], roles: ["opener"], rating: 79, cred: "Clean-striking top-order stylist" },

  // ===================== SOUTH AFRICA =====================
  { name: "Allan Donald", team: "SA", decades: ["1990s","2000s"], roles: ["pacer"], rating: 93, cred: "White Lightning — 330 Test wickets at 22" },
  { name: "Shaun Pollock", team: "SA", decades: ["1990s","2000s"], roles: ["allrounder","pacer"], rating: 90, cred: "421 Test wickets + 3,781 runs of nagging perfection" },
  { name: "Hansie Cronje", team: "SA", decades: ["1990s"], roles: ["allrounder","batter"], rating: 84, cred: "Hard-nosed 90s captain and clutch bat" },
  { name: "Gary Kirsten", team: "SA", decades: ["1990s","2000s"], roles: ["opener"], rating: 86, cred: "188* in a World Cup — then coached India to one" },
  { name: "Daryll Cullinan", team: "SA", decades: ["1990s"], roles: ["batter"], rating: 83, cred: "Supreme vs everyone (except one leggie)" },
  { name: "Jonty Rhodes", team: "SA", decades: ["1990s","2000s"], roles: ["batter"], rating: 84, cred: "That run-out. Changed fielding forever." },
  { name: "Dave Richardson", team: "SA", decades: ["1990s"], roles: ["keeper"], rating: 79, cred: "SA's first-choice gloves post-readmission" },
  { name: "Lance Klusener", team: "SA", decades: ["1990s","2000s"], roles: ["allrounder"], rating: 86, cred: "Zulu — Player of the 1999 World Cup" },
  { name: "Herschelle Gibbs", team: "SA", decades: ["1990s","2000s"], roles: ["opener"], rating: 86, cred: "175 in the 438 game; six sixes in a WC over" },
  { name: "Jacques Kallis", team: "SA", decades: ["1990s","2000s","2010s"], roles: ["allrounder"], rating: 96, cred: "13,289 Test runs AND 292 wickets. Cheat code." },
  { name: "Mark Boucher", team: "SA", decades: ["1990s","2000s","2010s"], roles: ["keeper"], rating: 87, cred: "999 international dismissals — most ever" },
  { name: "Makhaya Ntini", team: "SA", decades: ["2000s"], roles: ["pacer"], rating: 86, cred: "13/132 at Lord's — relentless wide-of-the-crease heat" },
  { name: "Graeme Smith", team: "SA", decades: ["2000s","2010s"], roles: ["opener"], rating: 89, cred: "Captain at 22; batted with a broken hand at the SCG" },
  { name: "AB de Villiers", team: "SA", decades: ["2000s","2010s"], roles: ["batter","keeper"], rating: 95, cred: "Mr 360 — fastest ODI 50, 100 and 150" },
  { name: "Hashim Amla", team: "SA", decades: ["2000s","2010s"], roles: ["opener","batter"], rating: 90, cred: "311* at The Oval — serenity at the crease" },
  { name: "Dale Steyn", team: "SA", decades: ["2000s","2010s"], roles: ["pacer"], rating: 95, cred: "Best strike rate of any 400-wicket bowler. The Steyn stare." },
  { name: "Morne Morkel", team: "SA", decades: ["2000s","2010s"], roles: ["pacer"], rating: 86, cred: "Throat-ball specialist from 6'5\"" },
  { name: "Vernon Philander", team: "SA", decades: ["2010s"], roles: ["pacer"], rating: 87, cred: "50 Test wickets in 7 games — seam-bowling surgeon" },
  { name: "Faf du Plessis", team: "SA", decades: ["2010s","2020s"], roles: ["batter"], rating: 86, cred: "Debut Test match-saving epic; IPL evergreen" },
  { name: "Quinton de Kock", team: "SA", decades: ["2010s","2020s"], roles: ["keeper","opener"], rating: 88, cred: "Left-handed lightning with gloves and bat" },
  { name: "Imran Tahir", team: "SA", decades: ["2010s"], roles: ["spinner"], rating: 85, cred: "Celebrates wickets somewhere near the boundary" },
  { name: "JP Duminy", team: "SA", decades: ["2000s","2010s"], roles: ["batter"], rating: 80, cred: "166 at the MCG announced him to the world" },
  { name: "Kagiso Rabada", team: "SA", decades: ["2010s","2020s"], roles: ["pacer"], rating: 91, cred: "300 Test wickets before turning 29" },
  { name: "Anrich Nortje", team: "SA", decades: ["2020s"], roles: ["pacer"], rating: 84, cred: "156kph thunderbolts in the IPL" },
  { name: "Lungi Ngidi", team: "SA", decades: ["2010s","2020s"], roles: ["pacer"], rating: 81, cred: "Big-match new-ball bursts" },
  { name: "Keshav Maharaj", team: "SA", decades: ["2010s","2020s"], roles: ["spinner"], rating: 85, cred: "SA's finest spinner since readmission" },
  { name: "Aiden Markram", team: "SA", decades: ["2010s","2020s"], roles: ["opener","batter"], rating: 85, cred: "Fastest World Cup hundred (49 balls)" },
  { name: "Heinrich Klaasen", team: "SA", decades: ["2020s"], roles: ["keeper","batter"], rating: 86, cred: "Most violent striker of spin on the planet" },
  { name: "David Miller", team: "SA", decades: ["2010s","2020s"], roles: ["batter"], rating: 84, cred: "Killer Miller — 35-ball T20I century" },
  { name: "Temba Bavuma", team: "SA", decades: ["2010s","2020s"], roles: ["opener","batter"], rating: 80, cred: "Gutsy top-order captain" },
  { name: "Marco Jansen", team: "SA", decades: ["2020s"], roles: ["allrounder","pacer"], rating: 84, cred: "7-foot left-arm swing with a long bat" },
  { name: "Tabraiz Shamsi", team: "SA", decades: ["2010s","2020s"], roles: ["spinner"], rating: 82, cred: "Left-arm wrist spin and shoe-phone celebrations" },
  { name: "Paul Adams", team: "SA", decades: ["1990s"], roles: ["spinner"], rating: 78, cred: "'Frog in a blender' action — unreadable chinaman" },

  // ===================== NEW ZEALAND =====================
  { name: "Glenn Turner", team: "NZ", decades: ["1970s","1980s"], roles: ["opener"], rating: 87, cred: "First Kiwi to 100 first-class hundreds" },
  { name: "Bevan Congdon", team: "NZ", decades: ["1970s"], roles: ["batter","allrounder"], rating: 81, cred: "Back-to-back 170s vs England" },
  { name: "Richard Collinge", team: "NZ", decades: ["1970s"], roles: ["pacer"], rating: 79, cred: "Left-arm spearhead of the 70s" },
  { name: "Ken Wadsworth", team: "NZ", decades: ["1970s"], roles: ["keeper"], rating: 76, cred: "Combative keeper-bat gone too soon" },
  { name: "Hedley Howarth", team: "NZ", decades: ["1970s"], roles: ["spinner"], rating: 77, cred: "Patient left-arm orthodox craftsman" },
  { name: "Richard Hadlee", team: "NZ", decades: ["1970s","1980s"], roles: ["pacer","allrounder"], rating: 96, cred: "431 Test wickets — a one-man attack" },
  { name: "Martin Crowe", team: "NZ", decades: ["1980s","1990s"], roles: ["batter"], rating: 92, cred: "NZ's greatest bat; reinvented ODI tactics in '92" },
  { name: "John Wright", team: "NZ", decades: ["1980s","1990s"], roles: ["opener"], rating: 84, cred: "Gritty opener, later India's beloved coach" },
  { name: "Ian Smith", team: "NZ", decades: ["1980s","1990s"], roles: ["keeper"], rating: 80, cred: "173 off 136 from No.9(!)" },
  { name: "Ewen Chatfield", team: "NZ", decades: ["1980s"], roles: ["pacer"], rating: 79, cred: "Hadlee's tireless partner in crime" },
  { name: "John Bracewell", team: "NZ", decades: ["1980s"], roles: ["spinner"], rating: 79, cred: "Fighting off-spin and lower-order runs" },
  { name: "Jeremy Coney", team: "NZ", decades: ["1980s"], roles: ["batter","allrounder"], rating: 80, cred: "The Mantis — brains of the 80s side" },
  { name: "Ken Rutherford", team: "NZ", decades: ["1990s"], roles: ["batter"], rating: 79, cred: "Stylish 90s middle-order captain" },
  { name: "Stephen Fleming", team: "NZ", decades: ["1990s","2000s"], roles: ["batter"], rating: 87, cred: "Smartest captain of his generation" },
  { name: "Nathan Astle", team: "NZ", decades: ["1990s","2000s"], roles: ["opener","batter"], rating: 83, cred: "222 off 168 balls in a Test. Still absurd." },
  { name: "Chris Cairns", team: "NZ", decades: ["1990s","2000s"], roles: ["allrounder"], rating: 87, cred: "Sixes for fun + genuine pace" },
  { name: "Adam Parore", team: "NZ", decades: ["1990s","2000s"], roles: ["keeper"], rating: 79, cred: "78 Tests of reliable glovework" },
  { name: "Daniel Vettori", team: "NZ", decades: ["1990s","2000s","2010s"], roles: ["spinner","allrounder"], rating: 88, cred: "Test cap at 18; 705 international wickets" },
  { name: "Shane Bond", team: "NZ", decades: ["2000s"], roles: ["pacer"], rating: 88, cred: "When fit, as quick and skiddy as anyone ever" },
  { name: "Scott Styris", team: "NZ", decades: ["2000s"], roles: ["allrounder"], rating: 80, cred: "Big-tournament over-achiever" },
  { name: "Jacob Oram", team: "NZ", decades: ["2000s","2010s"], roles: ["allrounder"], rating: 80, cred: "6'6\" of seam and six-hitting" },
  { name: "Brendon McCullum", team: "NZ", decades: ["2000s","2010s"], roles: ["keeper","opener"], rating: 88, cred: "Baz — 54-ball Test ton; invented Bazball" },
  { name: "Ross Taylor", team: "NZ", decades: ["2000s","2010s","2020s"], roles: ["batter"], rating: 87, cred: "290 in Perth; NZ's most-capped great" },
  { name: "Martin Guptill", team: "NZ", decades: ["2010s","2020s"], roles: ["opener"], rating: 84, cred: "237* in a World Cup knockout" },
  { name: "Kane Williamson", team: "NZ", decades: ["2010s","2020s"], roles: ["batter"], rating: 94, cred: "WTC-winning captain — calm in human form" },
  { name: "Trent Boult", team: "NZ", decades: ["2010s","2020s"], roles: ["pacer"], rating: 91, cred: "New-ball inswing nightmare" },
  { name: "Tim Southee", team: "NZ", decades: ["2010s","2020s"], roles: ["pacer"], rating: 87, cred: "7/33 vs England, WC 2015 — swing king" },
  { name: "Neil Wagner", team: "NZ", decades: ["2010s","2020s"], roles: ["pacer"], rating: 84, cred: "Bodyline reborn, with a smile" },
  { name: "BJ Watling", team: "NZ", decades: ["2010s"], roles: ["keeper"], rating: 82, cred: "Double ton in a WTC final build-up — ultimate scrapper" },
  { name: "Mitchell Santner", team: "NZ", decades: ["2010s","2020s"], roles: ["spinner","allrounder"], rating: 82, cred: "Choked India in the 2016 T20 WC" },
  { name: "Ish Sodhi", team: "NZ", decades: ["2010s","2020s"], roles: ["spinner"], rating: 80, cred: "Big-turning leggies in big tournaments" },
  { name: "Colin de Grandhomme", team: "NZ", decades: ["2010s","2020s"], roles: ["allrounder"], rating: 79, cred: "Medium pace, maximum nonchalance" },
  { name: "Devon Conway", team: "NZ", decades: ["2020s"], roles: ["opener","keeper"], rating: 85, cred: "200 at Lord's on Test debut" },
  { name: "Daryl Mitchell", team: "NZ", decades: ["2020s"], roles: ["batter","allrounder"], rating: 85, cred: "Tons vs India in India — fears nobody" },
  { name: "Tom Latham", team: "NZ", decades: ["2010s","2020s"], roles: ["keeper","opener"], rating: 84, cred: "Quietly one of the great keeper-openers" },
  { name: "Rachin Ravindra", team: "NZ", decades: ["2020s"], roles: ["allrounder","opener"], rating: 86, cred: "Three tons at WC 2023 — named after Rahul & Sachin" },
  { name: "Matt Henry", team: "NZ", decades: ["2010s","2020s"], roles: ["pacer"], rating: 83, cred: "Seam movement on demand" },
  { name: "Kyle Jamieson", team: "NZ", decades: ["2020s"], roles: ["pacer"], rating: 83, cred: "Player of the WTC final 2021" },
  { name: "Glenn Phillips", team: "NZ", decades: ["2020s"], roles: ["batter","keeper"], rating: 83, cred: "Human highlight reel in the field" },

  // ===================== SRI LANKA =====================
  { name: "Duleep Mendis", team: "SL", decades: ["1980s"], roles: ["batter"], rating: 81, cred: "Twin tons vs India in SL's early Test days" },
  { name: "Roy Dias", team: "SL", decades: ["1980s"], roles: ["batter"], rating: 80, cred: "SL's first world-class stroke-maker" },
  { name: "Arjuna Ranatunga", team: "SL", decades: ["1980s","1990s"], roles: ["batter","allrounder"], rating: 87, cred: "Captain Cool of '96 — walked to glory" },
  { name: "Aravinda de Silva", team: "SL", decades: ["1980s","1990s","2000s"], roles: ["batter"], rating: 91, cred: "Ton + 3 wickets in the '96 WC final" },
  { name: "Rumesh Ratnayake", team: "SL", decades: ["1980s"], roles: ["pacer"], rating: 78, cred: "Tearaway quick of the early years" },
  { name: "Asanka Gurusinha", team: "SL", decades: ["1980s","1990s"], roles: ["batter"], rating: 80, cred: "Rock of the '96 top order" },
  { name: "Sanath Jayasuriya", team: "SL", decades: ["1990s","2000s","2010s"], roles: ["opener","allrounder"], rating: 92, cred: "Master Blaster who rewrote powerplay batting" },
  { name: "Romesh Kaluwitharana", team: "SL", decades: ["1990s","2000s"], roles: ["keeper"], rating: 80, cred: "Little Kalu — pinch-hitting revolution, part 2" },
  { name: "Roshan Mahanama", team: "SL", decades: ["1990s"], roles: ["batter"], rating: 79, cred: "Part of a 576-run world record stand" },
  { name: "Hashan Tillakaratne", team: "SL", decades: ["1990s","2000s"], roles: ["batter"], rating: 79, cred: "Glue of the golden generation" },
  { name: "Muttiah Muralitharan", team: "SL", decades: ["1990s","2000s","2010s"], roles: ["spinner"], rating: 97, cred: "800 Test wickets. Eight hundred." },
  { name: "Chaminda Vaas", team: "SL", decades: ["1990s","2000s"], roles: ["pacer"], rating: 88, cred: "8/19 — best ODI figures ever" },
  { name: "Marvan Atapattu", team: "SL", decades: ["1990s","2000s"], roles: ["opener"], rating: 84, cred: "Six Test double hundreds" },
  { name: "Kumar Sangakkara", team: "SL", decades: ["2000s","2010s"], roles: ["keeper","batter"], rating: 95, cred: "Four straight WC hundreds in 2015; avg 57.40" },
  { name: "Mahela Jayawardene", team: "SL", decades: ["1990s","2000s","2010s"], roles: ["batter"], rating: 92, cred: "374 in Colombo; ton in a WC final" },
  { name: "Tillakaratne Dilshan", team: "SL", decades: ["2000s","2010s"], roles: ["opener"], rating: 86, cred: "Invented the Dilscoop, feared nothing" },
  { name: "Lasith Malinga", team: "SL", decades: ["2000s","2010s"], roles: ["pacer"], rating: 90, cred: "Slinga — 4 in 4 at a World Cup; death-over GOAT" },
  { name: "Upul Tharanga", team: "SL", decades: ["2000s","2010s"], roles: ["opener"], rating: 79, cred: "Elegant left-hander with big WC scores" },
  { name: "Rangana Herath", team: "SL", decades: ["2000s","2010s"], roles: ["spinner"], rating: 88, cred: "433 Test wickets — the quiet assassin" },
  { name: "Angelo Mathews", team: "SL", decades: ["2010s","2020s"], roles: ["allrounder","batter"], rating: 85, cred: "SL's crisis man for 15 years" },
  { name: "Dinesh Chandimal", team: "SL", decades: ["2010s","2020s"], roles: ["keeper","batter"], rating: 81, cred: "Test double ton vs Australia" },
  { name: "Dimuth Karunaratne", team: "SL", decades: ["2010s","2020s"], roles: ["opener"], rating: 84, cred: "World's most underrated Test opener" },
  { name: "Nuwan Kulasekara", team: "SL", decades: ["2000s","2010s"], roles: ["pacer"], rating: 79, cred: "Swing, smiles, and a WC final cameo" },
  { name: "Thisara Perera", team: "SL", decades: ["2010s"], roles: ["allrounder"], rating: 79, cred: "Six sixes in an over (List A)" },
  { name: "Wanindu Hasaranga", team: "SL", decades: ["2020s"], roles: ["spinner","allrounder"], rating: 86, cred: "T20 wicket machine with a golden arm" },
  { name: "Pathum Nissanka", team: "SL", decades: ["2020s"], roles: ["opener"], rating: 84, cred: "SL's first ODI double centurion" },
  { name: "Kusal Mendis", team: "SL", decades: ["2010s","2020s"], roles: ["keeper","batter"], rating: 82, cred: "176 vs Australia at 21" },
  { name: "Kusal Perera", team: "SL", decades: ["2010s","2020s"], roles: ["keeper","opener"], rating: 80, cred: "153* in Durban — greatest Test chase knock?" },
  { name: "Maheesh Theekshana", team: "SL", decades: ["2020s"], roles: ["spinner"], rating: 81, cred: "Carrom-ball heir to Murali's mystery" },
  { name: "Asitha Fernando", team: "SL", decades: ["2020s"], roles: ["pacer"], rating: 80, cred: "Skiddy new-ball menace" },
  { name: "Lahiru Kumara", team: "SL", decades: ["2020s"], roles: ["pacer"], rating: 78, cred: "Raw 145kph heat" },
  { name: "Dhananjaya de Silva", team: "SL", decades: ["2010s","2020s"], roles: ["batter","allrounder"], rating: 83, cred: "Classy tons + handy off-spin" },
  { name: "Charith Asalanka", team: "SL", decades: ["2020s"], roles: ["batter"], rating: 82, cred: "Left-handed middle-order spine" },

  // ===================== BANGLADESH =====================
  { name: "Habibul Bashar", team: "BAN", decades: ["2000s"], roles: ["batter"], rating: 76, cred: "Bangladesh's first batting mainstay" },
  { name: "Mohammad Ashraful", team: "BAN", decades: ["2000s","2010s"], roles: ["batter"], rating: 75, cred: "Test ton vs SL at 17 — youngest ever" },
  { name: "Mashrafe Mortaza", team: "BAN", decades: ["2000s","2010s"], roles: ["pacer"], rating: 80, cred: "Captain Narail Express — heart on both knees" },
  { name: "Shakib Al Hasan", team: "BAN", decades: ["2000s","2010s","2020s"], roles: ["allrounder"], rating: 89, cred: "World No.1 all-rounder in all 3 formats at once" },
  { name: "Tamim Iqbal", team: "BAN", decades: ["2000s","2010s","2020s"], roles: ["opener"], rating: 83, cred: "Ton at Lord's, name on the honours board" },
  { name: "Mushfiqur Rahim", team: "BAN", decades: ["2000s","2010s","2020s"], roles: ["keeper"], rating: 82, cred: "Mr Dependable — two Test double tons" },
  { name: "Mahmudullah", team: "BAN", decades: ["2010s","2020s"], roles: ["batter","allrounder"], rating: 79, cred: "Silent Killer — back-to-back WC hundreds" },
  { name: "Mustafizur Rahman", team: "BAN", decades: ["2010s","2020s"], roles: ["pacer"], rating: 83, cred: "The Fizz — cutters that broke India on debut" },
  { name: "Taskin Ahmed", team: "BAN", decades: ["2010s","2020s"], roles: ["pacer"], rating: 80, cred: "150kph leader of the new pace pack" },
  { name: "Mehidy Hasan Miraz", team: "BAN", decades: ["2010s","2020s"], roles: ["allrounder","spinner"], rating: 81, cred: "12 wickets to beat England as a teen" },
  { name: "Litton Das", team: "BAN", decades: ["2010s","2020s"], roles: ["keeper","opener"], rating: 80, cred: "Most aesthetic bat in Bangladesh history" },
  { name: "Najmul Hossain Shanto", team: "BAN", decades: ["2020s"], roles: ["batter"], rating: 79, cred: "Captain and top-order anchor" },
  { name: "Abdur Razzak", team: "BAN", decades: ["2000s","2010s"], roles: ["spinner"], rating: 76, cred: "First Bangladeshi to 200 ODI wickets" },

  // ===================== ZIMBABWE =====================
  { name: "Andy Flower", team: "ZIM", decades: ["1990s","2000s"], roles: ["keeper","batter"], rating: 88, cred: "World's No.1 Test batter while keeping wicket" },
  { name: "Grant Flower", team: "ZIM", decades: ["1990s","2000s"], roles: ["opener","allrounder"], rating: 79, cred: "The other Flower — gritty and versatile" },
  { name: "Heath Streak", team: "ZIM", decades: ["1990s","2000s"], roles: ["pacer","allrounder"], rating: 83, cred: "Zimbabwe's greatest ever bowler" },
  { name: "Alistair Campbell", team: "ZIM", decades: ["1990s","2000s"], roles: ["batter"], rating: 76, cred: "Stylish left-handed captain" },
  { name: "Neil Johnson", team: "ZIM", decades: ["1990s"], roles: ["allrounder","opener"], rating: 78, cred: "Star of the 1999 World Cup Super Six run" },
  { name: "Murray Goodwin", team: "ZIM", decades: ["1990s"], roles: ["batter"], rating: 78, cred: "Technically the tightest of his era" },
  { name: "Henry Olonga", team: "ZIM", decades: ["1990s","2000s"], roles: ["pacer"], rating: 75, cred: "Pace, principle, and the black armband" },
  { name: "Paul Strang", team: "ZIM", decades: ["1990s"], roles: ["spinner"], rating: 76, cred: "Leg-spin and lion-hearted lower-order runs" },
  { name: "Tatenda Taibu", team: "ZIM", decades: ["2000s","2010s"], roles: ["keeper"], rating: 77, cred: "Youngest Test captain ever at 20" },
  { name: "Brendan Taylor", team: "ZIM", decades: ["2000s","2010s","2020s"], roles: ["keeper","batter"], rating: 80, cred: "Back-to-back World Cup hundreds" },
  { name: "Sean Williams", team: "ZIM", decades: ["2010s","2020s"], roles: ["batter","spinner"], rating: 78, cred: "Zimbabwe's modern-day rock" },
  { name: "Sikandar Raza", team: "ZIM", decades: ["2010s","2020s"], roles: ["allrounder","spinner"], rating: 81, cred: "Carried a nation at the 2022 T20 WC" },
  { name: "Craig Ervine", team: "ZIM", decades: ["2010s","2020s"], roles: ["batter"], rating: 76, cred: "Calm left-handed captain" },
  { name: "Blessing Muzarabani", team: "ZIM", decades: ["2020s"], roles: ["pacer"], rating: 78, cred: "6'8\" of bounce and promise" },

  // ===================== AFGHANISTAN =====================
  { name: "Mohammad Nabi", team: "AFG", decades: ["2010s","2020s"], roles: ["allrounder","spinner"], rating: 82, cred: "The President — Afghanistan's first superstar" },
  { name: "Rashid Khan", team: "AFG", decades: ["2010s","2020s"], roles: ["spinner"], rating: 90, cred: "Fastest to 100 ODI wickets; T20's most wanted leggie" },
  { name: "Mujeeb Ur Rahman", team: "AFG", decades: ["2010s","2020s"], roles: ["spinner"], rating: 81, cred: "Mystery spin in the powerplay at 17" },
  { name: "Rahmanullah Gurbaz", team: "AFG", decades: ["2020s"], roles: ["keeper","opener"], rating: 82, cred: "Fearless six-hitting opener-keeper" },
  { name: "Ibrahim Zadran", team: "AFG", decades: ["2020s"], roles: ["opener"], rating: 82, cred: "First Afghan to a World Cup hundred" },
  { name: "Mohammad Shahzad", team: "AFG", decades: ["2010s"], roles: ["keeper"], rating: 78, cred: "Built like an uncle, bats like a dream" },
  { name: "Asghar Afghan", team: "AFG", decades: ["2010s","2020s"], roles: ["batter"], rating: 77, cred: "Captain of the rise" },
  { name: "Hashmatullah Shahidi", team: "AFG", decades: ["2010s","2020s"], roles: ["batter"], rating: 77, cred: "Led the 2023 WC giant-killing run" },
  { name: "Fazalhaq Farooqi", team: "AFG", decades: ["2020s"], roles: ["pacer"], rating: 80, cred: "Left-arm new-ball strikes" },
  { name: "Naveen-ul-Haq", team: "AFG", decades: ["2020s"], roles: ["pacer"], rating: 79, cred: "Death overs and main-character energy" },
  { name: "Azmatullah Omarzai", team: "AFG", decades: ["2020s"], roles: ["allrounder"], rating: 81, cred: "Genuine pace-bowling all-rounder" },
  { name: "Rahmat Shah", team: "AFG", decades: ["2010s","2020s"], roles: ["batter"], rating: 79, cred: "Afghanistan's classical No.3" },
];
